; Production PHP settings
expose_php            = Off
upload_max_filesize   = 10M
post_max_size         = 10M
memory_limit          = 256M
max_execution_time    = 60
max_input_time        = 60
default_socket_timeout = 60
date.timezone         = UTC
